---

- name: Install apt-transport-https package
  ansible.builtin.package:
      name: apt-transport-https
      state: latest
  async: 120
  poll: 10
  when: ansible_os_family == "Debian" and not ansible_check_mode

# INSTALLATION
- name: Add GitLab GPG key to APT
  ansible.builtin.get_url:
      url: "{{ gitlab_gpg_key_url }}"
      dest: /etc/apt/trusted.gpg.d/gitlab.asc
      mode: '0644'
  when: ansible_os_family == "Debian"

- name: Add GitLab repo to APT repositories
  ansible.builtin.apt_repository:
      repo: deb {{ gitlab_packages_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
      update_cache: true
  when: ansible_os_family == "Debian"

- name: Install GitLab package
  ansible.builtin.package:
      name: "{{ packages_to_install }}"
      state: latest
  async: 900
  poll: 10
  when: not ansible_check_mode

- name: Check installed GitLab package
  ansible.builtin.package:
      name: gitlab-ce
      state: latest
  when: ansible_check_mode

- name: Install necessary python modules
  ansible.builtin.pip:
      name: ['python-swiftclient', 'python-keystoneclient']
      state: latest

# CONFIGURATION
- name: Install gitlab configuration file
  ansible.builtin.template:
      src: gitlab.rb.j2
      dest: "/etc/gitlab/gitlab.rb"
      owner: root
      group: root
      mode: '0600'
  notify: Reconfigure gitlab

# BACKUP
- name: Copy Backup scripts on server
  ansible.builtin.template:
      src: "{{ item }}.j2"
      dest: /root/{{ item }}
      owner: root
      group: root
      mode: '0700'
  with_items: '{{ backup_scripts }}'
  when: inventory_hostname in groups.maintenance_contract

- name: Add cron job to execute backup
  ansible.builtin.cron:
      name: "{{ item.name }}"
      minute: "{{ item.minute | default('*') }}"
      hour: "{{ item.hour | default('*') }}"
      weekday: "{{ item.weekday | default('*') }}"
      job: "{{ item.job }}"
  with_items: '{{ backup_crons }}'
  loop_control:
      label: '{{ item.name }}'
  when: inventory_hostname in groups.maintenance_contract
